name: Build Perfect Xiaozhi

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    container:
      # 这里改成了最新版镜像，确保版本号 >= 5.5.2
      image: espressif/idf:latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          source /opt/esp/idf/export.sh
          
          # 进入源码文件夹
          cd Source/xiaozhi-esp32-2.2.2
